name: Brisk_Auto_Rent_A_Car_And_Garage
description: "Brisk_Auto_Rent_A_Car_And_Garage"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.5.4
  firebase_ui_auth: ^1.16.1
  firebase_ui_firestore: ^1.7.1
  cloud_firestore: ^5.6.8
  firebase_storage: ^12.4.6
  image_picker: ^0.8.6
  geolocator: ^9.0.2
  google_maps_flutter: ^2.2.0
  intl: ^0.20.2
  firebase_ui_storage: ^2.1.1
  firebase_core: ^3.13.1
  flutter_riverpod: ^2.6.1
  photo_view: ^0.14.0
  url_launcher: ^6.1.11
  font_awesome_flutter: ^10.7.0
  eva_icons_flutter: ^3.1.0
  image_compression: ^1.0.5
  path_provider: ^2.1.5
  uuid: ^4.5.1
  permission_handler: ^11.3.0
  google_maps_url_extractor: ^1.0.2
  http: ^1.2.0
  firebase_dynamic_links: ^6.1.7
  recase: ^4.1.0
  url_strategy: ^0.2.0
  shared_preferences: ^2.1.1
  printing: ^5.11.0
  pdf: ^3.11.0
  blue_thermal_printer: ^1.1.5
  flutter_native_splash: ^2.2.18
  flutter_launcher_icons: ^0.10.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true

fonts:
  - family: SocialIcons
    fonts:
      - asset: packages/firebase_ui_auth/fonts/SocialIcons.ttf
assets:
  - assets/logo.png

flutter_native_splash:
  color: "#000000"          # background color
  image: assets/logo.png  # your image
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center

flutter_icons:
  android: true           # generate for Android
  ios: true               # generate for iOS
  image_path: "assets/icon/logo.png"
