name: Brisk_Auto_Rent_A_Car_And_Garage
description: "Brisk_Auto_Rent_A_Car_And_Garage"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.5.4
  firebase_ui_auth: ^1.16.1
  firebase_ui_firestore: ^1.7.1
  cloud_firestore: ^5.6.8
  firebase_storage: ^12.4.6
  image_picker: ^0.8.6
  geolocator: ^9.0.2
  google_maps_flutter: ^2.2.0
  intl: ^0.20.2
  firebase_ui_storage: ^2.1.1
  firebase_core: ^3.13.1
  flutter_riverpod: ^2.6.1
  photo_view: ^0.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true

fonts:
  - family: SocialIcons
    fonts:
      - asset: packages/firebase_ui_auth/fonts/SocialIcons.ttf