// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQlqbUvtsVswXU81fcmQOfodOulQpdaZg',
    appId: '1:959391171995:web:0d4a7f57f61bc984168d3e',
    messagingSenderId: '959391171995',
    projectId: 'esentepebrisk',
    authDomain: 'esentepebrisk.firebaseapp.com',
    storageBucket: 'esentepebrisk.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqkIx4uSisM3_HTuKL5P4t8Bt74K7I4TU',
    appId: '1:959391171995:android:f9593d16ced5eea9168d3e',
    messagingSenderId: '959391171995',
    projectId: 'esentepebrisk',
    storageBucket: 'esentepebrisk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdZzuPNoFXZzR-HjQ0tHrK8_FIF2GWkUI',
    appId: '1:959391171995:ios:dd35145f93cf36e0168d3e',
    messagingSenderId: '959391171995',
    projectId: 'esentepebrisk',
    storageBucket: 'esentepebrisk.firebasestorage.app',
    iosBundleId: 'uk.co.gopcpitstop.esentepebrisk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdZzuPNoFXZzR-HjQ0tHrK8_FIF2GWkUI',
    appId: '1:959391171995:ios:99fea886ac207655168d3e',
    messagingSenderId: '959391171995',
    projectId: 'esentepebrisk',
    storageBucket: 'esentepebrisk.firebasestorage.app',
    iosBundleId: 'uk.co.gopcpitstop.esente',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQlqbUvtsVswXU81fcmQOfodOulQpdaZg',
    appId: '1:959391171995:web:ad8f9b43e3c14221168d3e',
    messagingSenderId: '959391171995',
    projectId: 'esentepebrisk',
    authDomain: 'esentepebrisk.firebaseapp.com',
    storageBucket: 'esentepebrisk.firebasestorage.app',
  );

}